#!/usr/bin/env bash

# get the script path http://stackoverflow.com/questions/4774054/reliable-way-for-a-bash-script-to-get-the-full-path-to-itself
pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd -P`
popd > /dev/null
ORIGINAL_WD=${PWD}
cd ${SCRIPTPATH}

if [ -f "./build/libs/ql-0.0.1-SNAPSHOT-all.jar" ]; then
    java -cp ./build/libs/ql-0.0.1-SNAPSHOT-all.jar io.xephon.proxy.ql.Shell
else
    echo "Please run 'gradle shadowJar' to build the executable jar"
fi

cd ${ORIGINAL_WD}
